export const ACTIVE_POS_REGISTER: string = 'ACTIVE_POS_REGISTER';
export const ACTIVE_POS_LOCATION: string = 'ACTIVE_POS_LOCATION';
export const ACTIVE_POS_LOCATION_NAME: string = 'ACTIVE_POS_LOCATION_NAME';